apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:4mjhMhOWT+k3pECHdToS9WRleWFdu4FdVXQwaly8Nyq/gu5puVez5rCAUmZyYDGlyQi1OJ4=,iv:E3cLHaGtqXIQTDM5w7CnQRo6H5D0W/nYON3iLHsVBUs=,tag:y35qtL0EgwXg6oK+GAQAMw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHdrTnJaMUxC
        ckFWRy9NWGM2VFFNZDZzYVZpQWFFT1FlSUdEZE90L0s0cTBkY04rdmE3K3NXYnlk
        ajBTT3NUelhqa25nanRCdk1qaE42M2hYcDRyeUt3MmFWdkhYaW10MDlNNEZHenpq
        VHV2TGlId1dEQit4MXFWbU5NRHlkckdhVTAvSm9vbjcrN0c1YkJQZHJrNkZJeG5Z
        bUEyeTl5V0NVMFVFMUFlOE9SajRyOERxYTVkSXJNa0dWNlpRUEZ4ZmZySExqejND
        Z3VOY1FGNmFtUWlVK1ZJUTdFNVF1QlErd0NBWEhUZEsvbGorMUVJVXg0VDJDNzZS
        NlJEOHNXeVFPUFdrMGI0elBBNUlTUm0yMDIyYThFWUw2ckV0dVdBcG9yWXlwMVhm
        a0FtdldQdFVGWE10Q3lZNGdOUEhyRUY3TmJIWWx0K2dhSSswOHBZK29relpMbEVZ
        a2hRWGZTQmVta3VPcHIzd0RSZnpUd0JjM21wZ210VVp0OFRNY1FteGQyVlkwdnp3
        MnVualg5cmc5UjN6eGNlRjBDWlpTdmkvSk5CbytNSm5tREFyUDgwN3JwdjZlcXVX
        dG1GK2IvOXp5RFpzbHFlUzhZZG5rUnc4ZVdXZ2lnK2pmUUJWZEtjeDhYOElLdzRD
        UnpVMDIzbmRyTlZ0eHdUMUxiZjlHbzFqK2NiMzRld2dKdFBJcEFKR2FSMHdSS3Z5
        UDNFNzN0dXUrcjhtaGdHOE9uL0lFYU1MSldHZEU0NTl5dWRWS0dlWldrRTAvVzBq
        VTJJZzBVSzY0V0pHTHZGSFlUQ1pSaTAzOEswQ2lnaGlFNmVrRmE5TXhGL2ZkdmFk
        SWg4SHVUVjN4OFNraVdwZmdFcGp1RTJab3ZaRzJ5ZHlNaHA4U3lVZ3B4UmxoRXRr
        emJXZG03a1dkdTU4Szg1L0h4YVNwalZ5N0VwcC9qdDg2aVJETG9sYnNxWkdVZTNK
        Uy9Vb1I2bjdxdlNtY3FRbGVETFZ2ZHdxWG1ROE8vZXBGRDhnMTVIa3BTMDFoK29l
        YkorZjk2STE2eTFvRzRKck9TRG5Hb3NnMmNlZFJpb1ZwclI4ZU0rQ3cxQ2FLcHpK
        N0hFUGFQRlVJOC9CZlU1UGdGMHFzZHd3am56Umx6V3dxTk8xK3hQUWJIbExhc1Bw
        bW93dGJVRXFLNFBRWnBwU25sNWFkZW55dlIrRXhJK01oWUxKckc3UGFHVkdWTDE2
        QkcvUWR4UTAzMFJrVk8zYVFCajZJWDM0SFZKQmtOSWlZYmhBbjZ0ckcxeE12SHlP
        Nlgrc0JiY2k4NldvTVBxM2IxTGNWUndhUENWbThuUFFUd3ZkSnUzNldtMEN4UENY
        Ukw1dDg3UkdvRXlpS0ozZ1RXVGZZMFlSc1RMWXpJWFN0c09ERTF1aVFtb2loeGIw
        T0tWRDlJY2pQeUtGK3pCb2Iya0hFSVVKa2Iwc2NYbHFLb2kzNjBaVVBBbjFSYnZy
        M3g0VEZCdktaTXV0Y0lFSEV5cG9GcUZQOEhaQmhxUFRTMEViMTEvTzFpaUpnaVpR
        WUM4cGRPNEhNRnE5bnpNTWNwZ21iZ3h3ZkNvY0tOa2ROUVlrTGxPQUdpeVJUYmd1
        bUNWOElISnNHa2pQT2QvZFpEZ0kxQVk4MVgvdk9uTmlEY0FCVytkVlBDd1dKcytZ
        SWxjeFkzUGVaS0VnWnJGZXI5WFpzTVY5YStuaVlyd3ZxU2FWc3lZSTJwY29Lek1F
        Qm9ZQWlBOTlwc1ozN1d4KzI5THl2T0JLc3haVlY3WFgzVUZHRTJqNHBoSXNNdWxU
        bG1NdVpyQW10Q1FYZ00wS1YyYWZKTE9WLzlwNFhiOC8rRjBHYmQ5RU5kRE5oNnV6
        dFkydXdXblVITzdmVTNleHFOYkU4TCtFd3NMMmJFREFDSHhnRDYzaEZlN01CcWda
        YnFDRTlJdzBoaHU0SDV0V0NOVFhRZkc0UDRSeEh4M0JaSWZTNkpyNmdkNThSZwpp
        Y0ljZzNxck1rejBvU3AyV2JuSktCZ3B1ZUtlMW16MUlVaE84OVR0T3FzCi0tLSBD
        OG1Dc0VZcEFWcEg5WGluYmozNGJFa1V3ekxLVkVWUFQ0bTJaVDNTd3JvCut6inW4
        arzgKfSFZJfAUadXgrFvkEWeEM8iP5HrBIJVpXrtDAnxpx1Vajrms1ppu1koYRqb
        TH/t0rc/iigRMDo=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1h4qft6jfcfunv584y65t26wdwu2263lpygttn96sq67777k2qrq9yalm88l8p89ku509exr5f3tsptljqggdv0j5qwdeqhz50dshsv84g7yt0z6vqcvdrfs2v7zhge6qdd0mgc3awg68zusuvy3z443p59cvry32ajyu297pguc5zxmq3ejzhsswh3sqx2qmg39sj3ukyl6yq4qj7cu4hdjn7md5p2kp2gh6jg85a9dt65cvd0fucluzk46dc04kyapnuy5w7f5998m2nkjmhdg5vkx0gwzxust4v69kq38aqyyfy2sqpvjqmvcqyy2j9ytaku2uwpl75npzhlcxqlergcxq57azyj45guy2wuz4wj2e0p8rwnw2samxru9k85zsgp9yykr3qp05j25673adfye8chvugayef8524d3ze2d6ay34jexstzheguf4fx42xtxqutequfljw34548wueg8y6ed43psxkuyc8ux2gwdlfp4gakqx2ewpl5xxhtarnyn77zps87q76t9q4ah534mtgmxyy578sg92cjskljhnjse8nt323du6z6g52znu3kx5cgnksnkhv3xd3q5rsmg65tfrrhc8vp43lz32aw383ynm5pmt40m8qucrjys2zc4eej78z2p90m65xczy8v4sv92ghcfj97zffuluxejm5pm7xq49d0eqg8n5drpzejk9f25y2t9ked6pg4kghf3rq2zt4jvxmgzff872g8sf5ypnyv0lsp3sgz37etmvarmxjxefzsdrqm95c7vh72r8ekfzsvjgqxa7vy00vsgw69r9sy0vjnq5fdx7p2m3pkqskek2e44rrqpfsq5cqec83g39aqw9hnat9vmv5aeh5f8rl3j5wadyew4ydy9pvrwjhf754vacvm4tssgcec2vsqjqyczh2c4pwxsg36jy3acg2trezfxen9yzrjutkkzc3qtqcw6kdsunywc559rp8zphgh8mwn0favpsd6rpk6uxnaezdrrd384gnf4asdfqveu4l6afphkug60pxk2ktaf3976zmy2zeyhy3t48zj42gzggr8uz0q3gd2xcrp9u8gvthu5k0v4p3yz2t6d7kkvxk6galpdhe69txxpefp5nkx0td3lxzzdt30dhpdyhhxlhn9ashn806kddzp55wpggfdkq30pr4x4n353qmsgpcqaj00nq5l075fvy0d4jaxzmdnp5jnqgw0hvmj3q5vp4khgz0u4y8gsfgcsyy7snha99gmaqmkm3ztf4kujtj2g67v7wwlp3ntnmj6yzy9vn4qr7u6y7qu7yvl8xkq2tvrgxaxqfrerl2kvk87tved2aslpj6znuwv6u9nvxnawc8xk9f3cldq0mm4rw9njkxhdr2lgx0ztqlyss4py32h4jmyr8jnmnj0mm5ryzhptw09up8s4tpedvxgyekp3ataxz36wtvyzpwyvwyafuxc35d3z9ftsqd7dfct4ncut5768ww5ydcpk229k3x03utsrrrt8a2xs0dj946tmshlexjkmlfx5c3srmfkppcc4rzh0fq6xu8zctzunec7q9raqpwgh49jzqarp0azkfl6syfm680frjv5wjh2d0uv9fknsedtnpny7xzexh0gthh2dt9afe7nazjsp5x9e9uj34d6jpplgvsurp0tqh3tj7vvhhg4nrttajh2e3gt8yj0p32xsl0kwxlwusn4gx8vpye96kz2vwk5u9pny93qr42zf25mz5693fuqz0admrja5s57lc0z5xysg37e20svrz4vshs53npt7z2ycp2u2s7vet6rfeqfa8zj94j3qzapufflvvn2fgswz89uv8zearg5p4ssauh9k4v9e77urzgdr3fdrjeg48hkfysecm6clvr72pw2xkvkcql4v5fy54n0hcf0lafqq2duaqyzey
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-05T11:41:40Z"
  mac: ENC[AES256_GCM,data:HME2vLX6ITc5bg5Qi1Sxunot/CwKNHOYWf4xTFiJFkjw3inBS79L6TkiYcwyO64DO/bXH9uqjXaG1VEIVMlDVfpoX3u0Ue81Qy5JU0vSPScQhq1I06QU4FQwcq/8JlhnMyh+apbnuHrzrtCLXDn0h33hAUepYLosh4UnMchMdjo=,iv:UqVHLUAmXIATIYviON7oNX+KT5eMYFEWRCUPa5MZp3o=,tag:GV4yxnj5uxTNpfhcsjpxEw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
