apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:lTjPNbK69ESbyJqD,iv:yg94+t75+oJCuxCUcrkf/GQc7OlTooiujTD4avc7+OM=,tag:AA0YIzsV4IPbOWEDbb2XaA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGh2eGFzVExU
        NHdKQnRydkE0YkYzZFVad3liSng2eFF2M2dtVjRnT1Q5WVRCWVBvSEwrWW9jWEVZ
        QVJEMEVodlU1LzRhc2k1eXNhdFdod0N3NW5PNHJvZGVqd3dCTHhVa0IxcVduMzY5
        RTZGR2ZTWkRDRldaMkpGZitObE51S3dKVTV2eUpHSXhrNXhyS0swUEthVDRZR1F5
        VjBMYkN0eTVRb1RUY2ZaaHc0SitOM0IrSzNmZml3ZGFiUzBZY2hTMHQ2RnF3ME1s
        bDF5MmxFSzVmL01IYUpPRWdpYWFkOUNrQUxEZXR5d1JXTnF4QmY1eTJCTlpVZzdL
        RTJOajBwNW52Z0k3Mmc4THptRWlrOTVyV0Z2eWx5SzNocFRVWTVEdm5KMG5uY3FQ
        S0s4THlmNU9HSU9ldDNVbVYrcWJBVWp6U1ZHYThTbWd0KzNzL3NHc3RhaDBiME1n
        bFZBTXd0UXRoNTh4WHNVR1I1MkIzZVVkOGl6OEZYMUJ6TVNDVkJLc0NSa1p2V0xB
        cjVlODBzMWQwZDJyVHFsSGQvMUVBVE5qdE9Ddmx2ZnJWRUlWT09ReTFwTUNpeUIr
        anZKNU4zU3UxTCtzTm9zUy9YOUxvckUrSW9McCtvaEtWalNPVVBGUWp4NzNzeE5a
        eGZIdTdFMEJ4aVVweG8rQi85YzdCV3dGYm9Uc1ZLcWl2NnY4RjdNZWgyRGNGajdw
        ZHBUbm1wOUk1M05xcTNJYjRuVi9Yd0RnZVNXZnZJVXpncTNjdzlIWFl0R1lORkRp
        MHk3YXZsZElQbVFjdDBDL3RmcFFYajNad1lvTnl5ZzJraGVta2swNDdSUGlsV1gx
        dkp0MUJENW14UUxNQ29nK0x5MDFqTDNJUjZXdGRZMHJXWE0yTFk1T3VITnhHVzUw
        bis0RGRoYW9HMkZVMjFycGNMWGppVitQOEtvMFdjVmN4OFVSQ1l3NkVmbUZhMTA0
        UzlnQ3ArT1pCSzl3S3U4OWM1elVpVEJ5TFJaK1dBamJ5N1I5WTJtNDdhd1lhbWVI
        c3pDSkxnSXdhN3BkSERwTjRLOFdxWk9VeDJUak9zQUFwTnpITHIwY1N5ajBWWWhY
        MWcyUzFRZTVXdFRNcS9vREVZTlNpa0ZNZ0ttYzNaRG54eXpBaXZiQ0F6TDFmODhJ
        WktwYlpKWldqTnlGckJIcjRVRS9ZRFdGdGJMTXZvSTZNSFpreDM2eVE2RGhkTklm
        WWFUU2R3Zk5Wam1FK1JPL3ZEV1hxNGdEak9WVysvUlU0ZXFmNitpdEY1aFJ4TE5y
        SDFPdGw2ZXR0K0xkUUNGbmxZOVJDVzFMZlN3Q1F2K255RlU0em91eDZJMnhwdWs2
        RG5SdVMzQVhMR1c1ekpYOXpsMVBTRmdUMXF2T3QzSnhRMWRReGp6NHFzcWhkdm9F
        MSsxMk1FcWZLLzFkV1BkSjdaTXZsbk1SaEsxTUNDclBTTlR2allPb2l5RndGNHRD
        U1JTbGpWakRlQzNWTmtIL1U0ckJOSDkvZDhMR0IrVVZrOUZselhQcXQvVDEvSUlB
        czloMDJ3TWdzTDJKMXloeStUWUw3NlYxYnZMVmVNdWpvajgzdkphWFJrZzlwY1JD
        OEdSdXd4bWp0c0ZUQzNPT1RZU1prTGRqM0g4clRiZlhwbzFzVmdubjZmSjR4OWFG
        OVZ0cDkrb3BPbE9abDViUzJmREdzaVV0eENlalRGWUlya3dCWXNVWkxoK2NXU1U4
        QStIMGtiTzFHUDg5aXRkNmRCejVIR2NNRHRIZ2FqeFRSWnRIQU1tWnVBeFlrUysy
        Rkp2UTNwdm5JSllYQkZZazZWcjBvc1ptMWJQb3RYYldLTzN6RW9qMTFvbVVydFBm
        Mm80Qi9HKzU2WHNzNk1oV2drMmZoTGE2ZjBPZ3VRNUNWeXFEaHBVcG5CSGl4eTg0
        T0JVTXBFZGQzZlVYL2R1b05FRFpsdXYzZE5oRnZWemlNQTdNd2hXbkdWQUFPdwpu
        ZjR3RWRyRjhRMlc1L3ZsQlRuNGtmd25QVTNJckExUVFHTFJrckQ1eWZvCi0tLSA3
        NzZ1aG95S29iUTdwL0p0V0hkT2V5K0FrL2pWTEZmazdCQm9VRC9aTVZVCoYsLccu
        FYtkITEFFQj5Yo3SIdE8AyGT+UXrVItemkPLqbKxsmZyeqgyYf6cu4Fuvxc7wXzr
        Sh/soQBLA0kYcpg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1h4qft6jfcfunv584y65t26wdwu2263lpygttn96sq67777k2qrq9yalm88l8p89ku509exr5f3tsptljqggdv0j5qwdeqhz50dshsv84g7yt0z6vqcvdrfs2v7zhge6qdd0mgc3awg68zusuvy3z443p59cvry32ajyu297pguc5zxmq3ejzhsswh3sqx2qmg39sj3ukyl6yq4qj7cu4hdjn7md5p2kp2gh6jg85a9dt65cvd0fucluzk46dc04kyapnuy5w7f5998m2nkjmhdg5vkx0gwzxust4v69kq38aqyyfy2sqpvjqmvcqyy2j9ytaku2uwpl75npzhlcxqlergcxq57azyj45guy2wuz4wj2e0p8rwnw2samxru9k85zsgp9yykr3qp05j25673adfye8chvugayef8524d3ze2d6ay34jexstzheguf4fx42xtxqutequfljw34548wueg8y6ed43psxkuyc8ux2gwdlfp4gakqx2ewpl5xxhtarnyn77zps87q76t9q4ah534mtgmxyy578sg92cjskljhnjse8nt323du6z6g52znu3kx5cgnksnkhv3xd3q5rsmg65tfrrhc8vp43lz32aw383ynm5pmt40m8qucrjys2zc4eej78z2p90m65xczy8v4sv92ghcfj97zffuluxejm5pm7xq49d0eqg8n5drpzejk9f25y2t9ked6pg4kghf3rq2zt4jvxmgzff872g8sf5ypnyv0lsp3sgz37etmvarmxjxefzsdrqm95c7vh72r8ekfzsvjgqxa7vy00vsgw69r9sy0vjnq5fdx7p2m3pkqskek2e44rrqpfsq5cqec83g39aqw9hnat9vmv5aeh5f8rl3j5wadyew4ydy9pvrwjhf754vacvm4tssgcec2vsqjqyczh2c4pwxsg36jy3acg2trezfxen9yzrjutkkzc3qtqcw6kdsunywc559rp8zphgh8mwn0favpsd6rpk6uxnaezdrrd384gnf4asdfqveu4l6afphkug60pxk2ktaf3976zmy2zeyhy3t48zj42gzggr8uz0q3gd2xcrp9u8gvthu5k0v4p3yz2t6d7kkvxk6galpdhe69txxpefp5nkx0td3lxzzdt30dhpdyhhxlhn9ashn806kddzp55wpggfdkq30pr4x4n353qmsgpcqaj00nq5l075fvy0d4jaxzmdnp5jnqgw0hvmj3q5vp4khgz0u4y8gsfgcsyy7snha99gmaqmkm3ztf4kujtj2g67v7wwlp3ntnmj6yzy9vn4qr7u6y7qu7yvl8xkq2tvrgxaxqfrerl2kvk87tved2aslpj6znuwv6u9nvxnawc8xk9f3cldq0mm4rw9njkxhdr2lgx0ztqlyss4py32h4jmyr8jnmnj0mm5ryzhptw09up8s4tpedvxgyekp3ataxz36wtvyzpwyvwyafuxc35d3z9ftsqd7dfct4ncut5768ww5ydcpk229k3x03utsrrrt8a2xs0dj946tmshlexjkmlfx5c3srmfkppcc4rzh0fq6xu8zctzunec7q9raqpwgh49jzqarp0azkfl6syfm680frjv5wjh2d0uv9fknsedtnpny7xzexh0gthh2dt9afe7nazjsp5x9e9uj34d6jpplgvsurp0tqh3tj7vvhhg4nrttajh2e3gt8yj0p32xsl0kwxlwusn4gx8vpye96kz2vwk5u9pny93qr42zf25mz5693fuqz0admrja5s57lc0z5xysg37e20svrz4vshs53npt7z2ycp2u2s7vet6rfeqfa8zj94j3qzapufflvvn2fgswz89uv8zearg5p4ssauh9k4v9e77urzgdr3fdrjeg48hkfysecm6clvr72pw2xkvkcql4v5fy54n0hcf0lafqq2duaqyzey
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-05T11:41:40Z"
  mac: ENC[AES256_GCM,data:EZeNARczHcRdnGiPcyrF60WTgl7nBL/WdO+BTIPqCkzpBWjZ1Y68nDI5v/YBeLUZ3h0ehGldO1XJAVnfIIN/46E3veu1N00SYocMZOaylVKA0L8mnF6S17i0UKlhI+65Q+3Lp1rYYc10Bf2bam3Kmy7ffxVBKYTs8Ge/nqH+XYI=,iv:cZYlIPmyBylXwzo1RgrZi5SSiL8LZtCXog1VgrUUSGo=,tag:vmjdK2T1Ekka9IxZHZVOsA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
