apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:paNZDAur5OrVECRJr8QewUit4wWrxePFeM3ZQnKtjzA=,iv:PJpU7fiwwEXVFBx3WvRUJl/Sk7nKUGyVFFJRsESNsi8=,tag:mH8qPu/qq2C4N22OjkOyeA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFdBZ0JlRVVG
        aFdCeEg1bWtjaWNHZHdGNXQ4eVBZWmFRcmFZTU94Q0txam00b1phQzk2Yk80SXFD
        T1Q3RUJHbHhEMVRUZ1huT3Uxb3Z2VENFNlJHMmFuakxPemdyVUdLZ3RINUJSWXNY
        cjhycTNmTUFiUjlQWlZDYzJ6R21icy8xMHFPQkJaaEJHdzBzaGE5d0REa2E1U3NQ
        cDBlYkRtM3BJd0E1aFBjeEw4c3VRVzhXbnVoT2V0L2trcmFiRkw0empVeWI5Wjhz
        M2t4S1hTaFBod3VyYk82QmpkWWxqaWxRN3RETGFjQWxBU3FjMGxVc1o3WFBjTjNn
        OGxyTzE0Uk5tK0gvci85dDBORGJ4S2YybzJUeEo4ZXloTmxYSW9ESGpCbnQ0WVZi
        Nk81QUU5ejBUYWdhbFpmUkI4WHkzV2ZhVGowa0lHVjF0RWFLK2dqWDlZc0MvZlRF
        SEhpRVFTU242eVZNd2l0cWRsZ25paUNjVGlvT2FaNFd2OTBaN1p3Y2NwQkZGNGVk
        amRCMUl6ZjNNcTIwNGo0aUVONE52YUN2bDRhM3BjaEhuUUdyamJURWo0cko4ZzVq
        eHU2dWFuLzRRUmVjOC9qQmZHS080MU0zTHRPNFR0c00rZXJHVlpVT0x4ZWJ5VjV2
        V2R2b3cxSFhVcGZzVHh5dkloT1J4YzBPY1FsUWRvNzhjKzVITEo1dzlWMzBTbnlY
        QnlUTWxDaXVEYnhvUktJUmhZd1F3Z0hXMHNZMTN4bHVxTUZQK09ZT2RabEZGSlo5
        aUtzUkgvQ2E0TEVqaVMzTUhNZ0pJSVdQTlJwM2l3RnNLYW42d29KQTM3ckNBOU4r
        YkxTR2ZMTHV4WlpKZjBQM3dERjU0MHkrblJvZkxZMWJYMUl6eTdGcjNHdU5KOFdk
        YzZhcktKdXhWNER2NEVOSGd4Q3d6d2x2eUp2bnpHWU91Y2syaklnV1ordzdnNnk3
        VW05d2tQYWtJYzMwOWErSURWSW1DZmllSW00bzcvQUo5elFkYVkzWXNuQjRLM0oy
        aGFvVUlzWlFkRFdiZkYxS09sVWNNNzdHRS81YU9sNE9VTHJvVmE5U2dHR0ZYM1or
        QW5JWHB0dWNvMUdGSFNGTWFOdlV1YzdxMFNQMVBLNEVIM3BLZDl2d1ZSekxyd2ZS
        ZXhSZkZ3clZtRkpGVkFPS3RwS2M4bG9CQ2FoTldhRG1sT3VJVFlyYnlXc2RLWFQv
        SWNWZGlRcGVkQkEwM3poN2h6bWdaRHVEUVFzT3dUcVJ6NHdoa2t0bVpCdVFtN1hE
        WGJCeGlPcENhUjQzMVc5OStpNTBCYkFQN3RqN25WdXBsdjVEa3RNSnJPZjJMWkZN
        eXJhSndYWnhLblVUM3EvOXRmd1l2ZG5hZjk3SkZIcXF0SHl2MTZveUh2NEY1RXNB
        bS9PbDNDdTlNNFBsZm9GelNQUzZnTzRzNDl4enFjUzd3R0F5LzVpMlBRTlpCK2RR
        V0dRZ2ZvT3YvQlQrWHorV2xnakpXaElCdE14SHh5ZElZK0V0TlZXVHEwNFZkVzB0
        SG9YRTc1WHdPR29qMlZUWTQyNEJjZDVMcHloZUpiZVVjbHVnTkkwaHVxSkhSUy80
        TW91bWVEeGNETmhzZklobjBCYTlWd1JGM3pXVkY0SkNwRXZyTHBKZm9JWk1xa2l6
        MlA0ZUZ1UU8vb01tNmN5SFhZRGxMVUZHL1hDWStYVnN0YjE1MlNLMCtSZzRBTFpI
        d0ZHcWc1bWZaVytlOERSUWpNMk9zdGhQV00vZ1BPZ2ZEdkRRRU0wRlNhcVV3SHJL
        ODREVkk0YjEzYXdUMUtYYjIrMm5ObHJEbUZuVDdVc2tITytYVWRMSllPUXBRd2Z4
        MHhQSmt4TjZUYlJmbCtpTXYwNHNnYUdMMDR2eFR3NzJ6b09IWUZEL1RhVlBNbjc4
        TUtlT25lWHJNa2s4VzhEM3B1QXJMbWhMRkh5MDN4M3V0SkFaODU0eXVhWUpFZwpK
        Rkl6N0h0dThJK0NtcHp1ZmZQRVlycmp6UHhzSUJLMndOcTl0YzVtVVg4Ci0tLSAx
        aVhQcndaNGxNTE1nWkRQMGRNc0dnZkxPQXU4MXY3Wlp6WG5uZEJYWmRFCsIcp8rn
        6i6aLnTD6npc/c97WIVcVb2O9jdOMxlvF8BbMakh33xxeP6NU87AsweYe6qSNAiq
        BRvJkWHvTL0t0+s=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1h4qft6jfcfunv584y65t26wdwu2263lpygttn96sq67777k2qrq9yalm88l8p89ku509exr5f3tsptljqggdv0j5qwdeqhz50dshsv84g7yt0z6vqcvdrfs2v7zhge6qdd0mgc3awg68zusuvy3z443p59cvry32ajyu297pguc5zxmq3ejzhsswh3sqx2qmg39sj3ukyl6yq4qj7cu4hdjn7md5p2kp2gh6jg85a9dt65cvd0fucluzk46dc04kyapnuy5w7f5998m2nkjmhdg5vkx0gwzxust4v69kq38aqyyfy2sqpvjqmvcqyy2j9ytaku2uwpl75npzhlcxqlergcxq57azyj45guy2wuz4wj2e0p8rwnw2samxru9k85zsgp9yykr3qp05j25673adfye8chvugayef8524d3ze2d6ay34jexstzheguf4fx42xtxqutequfljw34548wueg8y6ed43psxkuyc8ux2gwdlfp4gakqx2ewpl5xxhtarnyn77zps87q76t9q4ah534mtgmxyy578sg92cjskljhnjse8nt323du6z6g52znu3kx5cgnksnkhv3xd3q5rsmg65tfrrhc8vp43lz32aw383ynm5pmt40m8qucrjys2zc4eej78z2p90m65xczy8v4sv92ghcfj97zffuluxejm5pm7xq49d0eqg8n5drpzejk9f25y2t9ked6pg4kghf3rq2zt4jvxmgzff872g8sf5ypnyv0lsp3sgz37etmvarmxjxefzsdrqm95c7vh72r8ekfzsvjgqxa7vy00vsgw69r9sy0vjnq5fdx7p2m3pkqskek2e44rrqpfsq5cqec83g39aqw9hnat9vmv5aeh5f8rl3j5wadyew4ydy9pvrwjhf754vacvm4tssgcec2vsqjqyczh2c4pwxsg36jy3acg2trezfxen9yzrjutkkzc3qtqcw6kdsunywc559rp8zphgh8mwn0favpsd6rpk6uxnaezdrrd384gnf4asdfqveu4l6afphkug60pxk2ktaf3976zmy2zeyhy3t48zj42gzggr8uz0q3gd2xcrp9u8gvthu5k0v4p3yz2t6d7kkvxk6galpdhe69txxpefp5nkx0td3lxzzdt30dhpdyhhxlhn9ashn806kddzp55wpggfdkq30pr4x4n353qmsgpcqaj00nq5l075fvy0d4jaxzmdnp5jnqgw0hvmj3q5vp4khgz0u4y8gsfgcsyy7snha99gmaqmkm3ztf4kujtj2g67v7wwlp3ntnmj6yzy9vn4qr7u6y7qu7yvl8xkq2tvrgxaxqfrerl2kvk87tved2aslpj6znuwv6u9nvxnawc8xk9f3cldq0mm4rw9njkxhdr2lgx0ztqlyss4py32h4jmyr8jnmnj0mm5ryzhptw09up8s4tpedvxgyekp3ataxz36wtvyzpwyvwyafuxc35d3z9ftsqd7dfct4ncut5768ww5ydcpk229k3x03utsrrrt8a2xs0dj946tmshlexjkmlfx5c3srmfkppcc4rzh0fq6xu8zctzunec7q9raqpwgh49jzqarp0azkfl6syfm680frjv5wjh2d0uv9fknsedtnpny7xzexh0gthh2dt9afe7nazjsp5x9e9uj34d6jpplgvsurp0tqh3tj7vvhhg4nrttajh2e3gt8yj0p32xsl0kwxlwusn4gx8vpye96kz2vwk5u9pny93qr42zf25mz5693fuqz0admrja5s57lc0z5xysg37e20svrz4vshs53npt7z2ycp2u2s7vet6rfeqfa8zj94j3qzapufflvvn2fgswz89uv8zearg5p4ssauh9k4v9e77urzgdr3fdrjeg48hkfysecm6clvr72pw2xkvkcql4v5fy54n0hcf0lafqq2duaqyzey
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-05T11:41:40Z"
  mac: ENC[AES256_GCM,data:OK+RpDYF9ijPk92BHkArPjEV2EfgZmyWLmdoTTYcfe9EExYByF096UzitGLV5ZIt5VlX2iQoCGQgpf+cTz8zWHsmiKylR0th51nb+nQLKKsvy/q9uDcQ2rOqeKQgNYEVsYQHnhHI/ArgFH8vkloS+GMfO98uaxbx7hcJyzRn1Vk=,iv:lviaTqiRfMezsTIup9kmJXL+K7Kg6P8pYFvo5VRL2bs=,tag:y4ypOvTEifIxs/AzRB+I4g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
