apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:AP562ncbIT3Hlc55s1LsJdN8PzZAxQ5KCEUkZZb5G+zt05yTvswvFaxEV6FlQL5JxdebR2S0FE3qSatoy8Tj+s6QQG6pJlWKaD4/x5fEcqYbtxHPUyclafJ5lMze+Ri28qjz2b9BJ2itzp/OCA32FsjdlCwgbrsfflkW4OrnX3LGjvN82XdpJf5ItJxDzAzwv/O+Ay2zKr2BdJ2JsGYVcHxEymlbnh0YYr6bO0z6dSLcg2Nu,iv:wff6xQvU6GDZl7M+9i1qJN0DQWwuIgAGeXJag8D4UcE=,tag:PmqKZYROYHHpFfUUw9B+2g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFZZbUwyTkZD
        dHp5Vks4ZlR2U0tQMzhuM2ZpTitaZEpEMWZ6ZlFXQUl0YTZaSFJIeEhpd3ZhWmRx
        aHhxUzRrVlNDVjdhNlVJK1lPMm5wRUtmVkZKTWdkY2tHVGZQb0lLeTFZalh0OVA1
        N3F1VWFWVkZJSE5FajFxQnFDWVlOMkdLNWUwa3NmdlBMMDlNTHNVbCtDd1ltc2Rk
        MUs3ZVRPNktJaWIwSjVnbVh1cjlhbW8xNHd3dUQxeTM4LzFHS0NSNE82TDRvZXIr
        VkVvdWFlWWdYTldYSkNKU2JhVUhlNXAza1JNZjN3dzRCQ0tiaXpocGh4YUk5K1FQ
        YS9IckV5eWNCNGhZdDM4bWtBMkZmbWluOC91VjQ3ZExBYkpZaVRTVStNL2V0M1NK
        dnFDNXZhbnlHR2Z2dkhqS1kvbC9udm9COFQ1QU5veDlXWXZBVXBUalphMUZBWW5T
        OW03Y3YvUm9RTUc4MW03SFJMM1lJUXV1M2w2U1RMM3RnTFdWR3dUS251czFaVGhS
        UlNZYkd3bTFpc0xTRGFQaVpsZmlJcDkxOUJGdWEyZW1LRUN2MllBd09tOXpJc2g0
        aGR3MDdBb3hCWXluNEdCZVZRWWtwQ01odlZWRTlzWERDaDZJZWRZWnQrWlNtaXBM
        REtmYVdXVWZtN1plVU9naTA0cENVZDRoZWUySEc3WVpSUi84aisyTmdBMmJoYmFF
        ZlRCeHc5VkFJY3ZCTWNKRDVBRnIyNVRIWFZhMW9ndWUyNWtyS3grdVVyY2RuUUVV
        U24vajkyZDFLd3NtYmNhWHRRZThkaXh6SkNNZjJ4YUh2SEhEeVBhYUNNWkRWenBH
        cFJXTUdMN1V6OWdmb1BNeS9kNUx6UDU4TmdybC9aSmUxRDd4VFN0ZTZvdUlTeDg1
        M3BUd2hBc3RxZ1VkUGdkMFZxVDVVTTF6TXFwcTBocFRXRnJSZ3VnL1RrdmZlT3h3
        eVpFOWNQRHNVdnlMUlZ3SUljeHdEUlpBRmx0TkY4ZmZFMExJM1M0amt6RzF4TWRK
        ZmdJZUYvZnUwMGNXV0xycFZGMnFNR3FiVENkeW9uRGhMSFptRGY5eS85VnRsdXJK
        LzNpdHhyb2hkT0NueTRSbUh2N2RQazlqUi9GN0szdGVySXp3WGpTRUR3S3dnNmU5
        cHBWRzhBZXBVVXJvb2ZtRkJRQlNSdFdidUVGOFdPVEJsTHp4OEJKa1dwWVJIODFN
        dFFyYjVYdEdBWGZPQ1R6S2RkRkQrOUhXYmpnN1IxaDRCMHh2eVJGU2ZGM1ZqZ3Qv
        bDFWSDFhdzZxZmJmeiswQU9RbXp3R3lrL09UMmcrOUdoc3h2ZHczNmxEV1g0SGhK
        WEtWM1c1MG9wUkN0clNXZVRveDlNQVZpSTVoWXV3OTZKRXhoUDhKMS9GUjNXK1hE
        Y2lvL0diUHZKTmUzMGdUS1JMVjByQU9aOUxyWGFmWGtoUnFCVXZWSTF2Y2c2dkJt
        dW9RMWJMKzRUVHNtYjFCRlNiUmh5MlZCNmMvUk9QWDkvclBZUnM5RmJHUHJmQlpq
        RUdUK28rQVJxTE9HOFBtM3VCTVNMaGNtYnRCZ1hTZS9GbUVuTzdBQ1FrRjBHMjRR
        bVQ0RGR5bnFWWUdlRklSajJCdFFSMkg3UDNrcGdUcjB4UzhGcjZTZkZnUE5MelRm
        RzYvM3RmSDBxZVNTTXdKc1FBRmtNbzQ2a0V5NFl5WGdoMmY3WW80VXQ5b2pqZ0lq
        Uy9UK3hKT0QxUVNpYzlFaW1GL1o1Zi9URHRyWG1UQjQ3Z2t1NFpTTDVURlNvRFNR
        YW9tcWlJc3VUT09LaTJ6UjZHYnNIMWRXbGxwMCs0SEhPb3lLR1A0NEtxOW92MVBn
        a0pEb2FEVkhtd0dEWHVYdXFJQVVLNktTWGhHbWNSOEJObFVhNzVKQWtnYlBGSmYr
        aDlKWUZvTDBWWU9Cbk03dGlvdVhsZzB3bW5SUmZLMUwwYlB2d1dDOCt0M2xCZwpi
        YWZqNmt6dXhqZGJEMWY1cWdPd2l5RWVzOTZKZkN3ZXJ6cC8vZzYwWFhZCi0tLSBu
        NjVRNFdaZTdNZDROTDgxL2NYMWU3Nmo5OWovVUc5dkJGS204L3Y1WmZrCh2Y6YvS
        X0EH2UCdxdAVzFXLrYmlf4Wcvnyql5HjOpT9POLEr/mBdyd1lw5m2CwOcKC8Vb0q
        mrbMv935KWcvLVE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1h4qft6jfcfunv584y65t26wdwu2263lpygttn96sq67777k2qrq9yalm88l8p89ku509exr5f3tsptljqggdv0j5qwdeqhz50dshsv84g7yt0z6vqcvdrfs2v7zhge6qdd0mgc3awg68zusuvy3z443p59cvry32ajyu297pguc5zxmq3ejzhsswh3sqx2qmg39sj3ukyl6yq4qj7cu4hdjn7md5p2kp2gh6jg85a9dt65cvd0fucluzk46dc04kyapnuy5w7f5998m2nkjmhdg5vkx0gwzxust4v69kq38aqyyfy2sqpvjqmvcqyy2j9ytaku2uwpl75npzhlcxqlergcxq57azyj45guy2wuz4wj2e0p8rwnw2samxru9k85zsgp9yykr3qp05j25673adfye8chvugayef8524d3ze2d6ay34jexstzheguf4fx42xtxqutequfljw34548wueg8y6ed43psxkuyc8ux2gwdlfp4gakqx2ewpl5xxhtarnyn77zps87q76t9q4ah534mtgmxyy578sg92cjskljhnjse8nt323du6z6g52znu3kx5cgnksnkhv3xd3q5rsmg65tfrrhc8vp43lz32aw383ynm5pmt40m8qucrjys2zc4eej78z2p90m65xczy8v4sv92ghcfj97zffuluxejm5pm7xq49d0eqg8n5drpzejk9f25y2t9ked6pg4kghf3rq2zt4jvxmgzff872g8sf5ypnyv0lsp3sgz37etmvarmxjxefzsdrqm95c7vh72r8ekfzsvjgqxa7vy00vsgw69r9sy0vjnq5fdx7p2m3pkqskek2e44rrqpfsq5cqec83g39aqw9hnat9vmv5aeh5f8rl3j5wadyew4ydy9pvrwjhf754vacvm4tssgcec2vsqjqyczh2c4pwxsg36jy3acg2trezfxen9yzrjutkkzc3qtqcw6kdsunywc559rp8zphgh8mwn0favpsd6rpk6uxnaezdrrd384gnf4asdfqveu4l6afphkug60pxk2ktaf3976zmy2zeyhy3t48zj42gzggr8uz0q3gd2xcrp9u8gvthu5k0v4p3yz2t6d7kkvxk6galpdhe69txxpefp5nkx0td3lxzzdt30dhpdyhhxlhn9ashn806kddzp55wpggfdkq30pr4x4n353qmsgpcqaj00nq5l075fvy0d4jaxzmdnp5jnqgw0hvmj3q5vp4khgz0u4y8gsfgcsyy7snha99gmaqmkm3ztf4kujtj2g67v7wwlp3ntnmj6yzy9vn4qr7u6y7qu7yvl8xkq2tvrgxaxqfrerl2kvk87tved2aslpj6znuwv6u9nvxnawc8xk9f3cldq0mm4rw9njkxhdr2lgx0ztqlyss4py32h4jmyr8jnmnj0mm5ryzhptw09up8s4tpedvxgyekp3ataxz36wtvyzpwyvwyafuxc35d3z9ftsqd7dfct4ncut5768ww5ydcpk229k3x03utsrrrt8a2xs0dj946tmshlexjkmlfx5c3srmfkppcc4rzh0fq6xu8zctzunec7q9raqpwgh49jzqarp0azkfl6syfm680frjv5wjh2d0uv9fknsedtnpny7xzexh0gthh2dt9afe7nazjsp5x9e9uj34d6jpplgvsurp0tqh3tj7vvhhg4nrttajh2e3gt8yj0p32xsl0kwxlwusn4gx8vpye96kz2vwk5u9pny93qr42zf25mz5693fuqz0admrja5s57lc0z5xysg37e20svrz4vshs53npt7z2ycp2u2s7vet6rfeqfa8zj94j3qzapufflvvn2fgswz89uv8zearg5p4ssauh9k4v9e77urzgdr3fdrjeg48hkfysecm6clvr72pw2xkvkcql4v5fy54n0hcf0lafqq2duaqyzey
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-05T11:41:40Z"
  mac: ENC[AES256_GCM,data:slmxeGNATE0mOXVOcSDU/gkp15zJzUQ+QdwqhcUTgxgwGJ0d/5N6JWRP7W0DHGsBAdsub9r0cwh0JjGuq1jrUIaThTdRE2YLL0a8F0NjpH3OWRhreiPZCd/hPKP6LX3Vi7WHmZznl6o4z9xVg3iLs8FPgZTvI49ta3qVQaxOpSk=,iv:YsnE74Imr8nsUZdUs9nK/INR17LzRvwRODGYwkEPVxM=,tag:RgnsXGqmhNWyASNeDfChmQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
